### ISSUE TITLE
Failed to execute script idasen-ui

### ISSUE THREAD

**Issue by plhosk** [danieldesrochers/idasen-ui#1]
Windows 10 latest
idasen-ui-1.1.0.zip (win32 build)

Unzipped the contents of the zip and double clicked idasen-ui.exe. I get the error dialog with the window title "Fatal error detected" and the text "Failed to execute script idasen-ui" with an OK button.

**Comment by danieldesrochers** [comment]
Hello,
the build is based on Python 3.8 installer. Few things to double-check, 
- make sure you are admin of your pc. 
- make sure that you have bluetooth enabled and desk is connect in Windows settings

If this is not working, I will add a wiki doc to install step by step and run the script directly from Python without exe

**Comment by lannetscan** [comment]
I've also experienced this issue. What was weird is that I don't know how to reproduce it. It happened when:
1. I was using release 1.0.0 all the time.
2. I downloaded 1.1.0 and checked it out.
3. 1.0.0 started causing the described issue, while 1.1.0 was working fine.

**Comment by kabakakao** [comment]
I have the same issue. It is not working for me :(
I have tried to "Start as Administrator" with the same result

**Comment by hpace8** [comment]
Ya, same. Downloaed 1.1.0, unzipped, tried to run idasen-iu.exe. The Windows hourglass comes on for a few seconds, then nothing happens. Tried pairing the laptop with the Idasen desk first, same result. 
This is on Windows 10.

**Comment by danieldesrochers** [comment]
Ok, will investigate that. It might be a missing package or something different than my setup.
@hpace8 could you please send me your idasen config file located in 
C:\users\<youruser>\.config\idasen-ui\idasen-ui.yaml
Thanks,

**Comment by superpsych0** [comment]
Echoing everyone else on this one, unzipped 1.1.0 into C:\Program Files, ran the .exe and nothing, ran as Admin, nothing.

Desk is connected, can see it through BT.

Really hoping you get this working once again, would be a tremendous boon to a whole lot of people!

**Comment by danieldesrochers** [comment]
Hello all, I just push version 1.1.1. This version is instrumented to help investigate the issue that you have.
- Unzip version 1.1.1 to c:\temp
- Run c:\temp\idasen-ui\idasen-ui.exe
- Normally, the application will not run on your PC
- Open the generated log file c:\temp\idasen-ui\myapp.log
- Copy-and-paste the content of the file here.

**Comment by danieldesrochers** [comment]
Hi guys,
I was able to reproduce the loading issue. Found the bug in the Python installer packaging the EXE.
Please try version 1.1.2, 
it should now work as documented.

**Comment by danieldesrochers** [comment]
Version 1.1.2 is fixing this issue.

**Comment by hpace8** [comment]
Awesome! Thanks Daniel!

**Comment by danieldesrochers** [comment]
> Awesome! Thanks Daniel!

hpace8 do you confirm that it resolved or if you still have the issue?

**Comment by danieldesrochers** [comment]
Finally resolved all UAC security issue by switching to NSIS installer.
= Release 1.3.0 =
    * Changed application installation to NSIS installer
    * Added shortcut in Windows Start Menu
    * Added uninstall option in registry settings
    * Fixed .NET Framework UAC security issue

**Comment by jiroumu** [comment]
Adding to here I'm still having this issue. Tried 1.3.0 and 1.1.2 with no success.
Windows 10 Enterprise 20H2
19042.804
Windows Feature Experience Pack 120.2212.551.0

Tried with elevated privileges and both with the desk connected via W10 BT and once without.

<img width="197" alt="1" src="https://user-images.githubusercontent.com/65429375/109988099-7cfb0200-7d07-11eb-8c45-88099dfb5cf9.png">
<img width="144" alt="3" src="https://user-images.githubusercontent.com/65429375/109988100-7d939880-7d07-11eb-9871-102b0b6b2a1d.png">
<img width="308" alt="2" src="https://user-images.githubusercontent.com/65429375/109988101-7e2c2f00-7d07-11eb-909b-5da627efa996.png">

**Comment by akbarahs** [comment]
> Adding to here I'm still having this issue. Tried 1.3.0 and 1.1.2 with no success. Windows 10 Enterprise 20H2 19042.804 Windows Feature Experience Pack 120.2212.551.0
> 
> Tried with elevated privileges and both with the desk connected via W10 BT and once without.
> 
> <img alt="1" width="197" src="https://user-images.githubusercontent.com/65429375/109988099-7cfb0200-7d07-11eb-8c45-88099dfb5cf9.png">
> 
> <img alt="3" width="144" src="https://user-images.githubusercontent.com/65429375/109988100-7d939880-7d07-11eb-9871-102b0b6b2a1d.png">
> 
> <img alt="2" width="308" src="https://user-images.githubusercontent.com/65429375/109988101-7e2c2f00-7d07-11eb-909b-5da627efa996.png">

I have exactly the same issue.
