### ISSUE TITLE
Minimize/close to tray

### ISSUE THREAD

**Issue by lannetscan** [danieldesrochers/idasen-ui#2]
It would be great if there was a possibility to minimize/close the UI and only have an icon the system tray.

**Comment by danieldesrochers** [comment]
good idea! will add this to the todo list.

**Comment by danieldesrochers** [comment]
= Release 1.3.0 =
    * Changed application installation to NSIS installer
    * Added shortcut in Windows Start Menu
    * Added uninstall option in registry settings
    * Fixed .NET Framework UAC security issue
    
= Release 1.2.0 =
    * Added minimize to tray option    
    * Added right-click menu to control tray option
    * Added minimize_to_tray setting in configuration
